[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.partitions = partitions_msc.csv
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

build_unflags =
    -DARDUINO_USB_MODE

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=0

lib_deps =
  git+https://github.com/xreef/SimpleFTPServer.git#v3.0.2

monitor_port = /dev/cu.usbmodem53140032081
monitor_speed = 115200
extra_scripts =
    pre:upload_reenum_hook.py
    post:upload_post_reset.py
